Repository Jeju-Dorang/Frontend, pull requests merged in 2024-09, with the labels that each got.

#38 Dev feat/#37
  JejuDorang/package-lock.json
  JejuDorang/package.json
  JejuDorang/src/apis/README.md
  JejuDorang/src/apis/index.tsx
  JejuDorang/src/apis/postLogin.ts
  JejuDorang/src/components/LoginButton/index.tsx
  JejuDorang/src/constants/url.ts
Labels: ♻️refactor, ✨feat

#39 Dev feat/#35
  JejuDorang/package-lock.json
  JejuDorang/package.json
  JejuDorang/src/app/Record/page.tsx
  JejuDorang/src/components/CustomCalendar/index.css
  JejuDorang/src/components/CustomCalendar/index.tsx
  JejuDorang/src/components/DayRecord/index.tsx
  JejuDorang/src/components/Footer/index.tsx
  JejuDorang/tailwind.config.js
Labels: ✨feat

#41 Merge: 주간머지
  JejuDorang/assets/img/login/jejuDorang.webp
  JejuDorang/assets/img/login/kakaoLogin.webp
  JejuDorang/package-lock.json
  JejuDorang/package.json
  JejuDorang/src/apis/README.md
  JejuDorang/src/apis/index.tsx
  JejuDorang/src/apis/postLogin.ts
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/Login/page.tsx
  JejuDorang/src/app/Main/page.tsx
  JejuDorang/src/app/Record/page.tsx
  JejuDorang/src/components/Community/index.tsx
  JejuDorang/src/components/CustomCalendar/index.css
  JejuDorang/src/components/CustomCalendar/index.tsx
  JejuDorang/src/components/DayRecord/index.tsx
  JejuDorang/src/components/Footer/index.tsx
  JejuDorang/src/components/LoginButton/index.tsx
  JejuDorang/src/components/Story/index.tsx
  JejuDorang/src/constants/url.ts
  JejuDorang/src/types/storyItem.ts
  JejuDorang/tailwind.config.js
  JejuDorang/tsconfig.json
Labels: Merge

#44 Dev feat/#35
  JejuDorang/assets/img/diaryDefault.webp
  JejuDorang/src/apis/getDiary.ts
  JejuDorang/src/components/DayRecord/CustomCalendar/index.css
  JejuDorang/src/components/DayRecord/CustomCalendar/index.tsx
  JejuDorang/src/components/DayRecord/Story/index.tsx
  JejuDorang/src/components/DayRecord/WriteDiary/index.tsx
  JejuDorang/src/components/DayRecord/index.tsx
  JejuDorang/src/components/LoginButton/index.tsx
  JejuDorang/src/constants/maxTextLength.ts
  JejuDorang/src/constants/url.ts
Labels: ✨feat

#43 Dev feat/#19
  JejuDorang/assets/img/back.svg
  JejuDorang/assets/img/chat/send.webp
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/Dorang/page.tsx
  JejuDorang/src/components/ChatDetail/Chat/DorangMessage/index.tsx
  JejuDorang/src/components/ChatDetail/Chat/Header/index.tsx
  JejuDorang/src/components/ChatDetail/Chat/InputMessage/index.tsx
  JejuDorang/src/components/ChatDetail/Chat/UserMessage/index.tsx
  JejuDorang/src/components/ChatDetail/Chat/index.tsx
  JejuDorang/src/components/ChatDetail/Onboarding/InterestBox/index.tsx
  JejuDorang/src/components/ChatDetail/Onboarding/index.tsx
  JejuDorang/src/components/ChatDetail/index.tsx
  JejuDorang/src/components/ChatMainHeader/index.tsx
  JejuDorang/src/types/chat.d.ts
Labels: ✨feat

#46 Dev feat/#45
  JejuDorang/src/apis/auth.ts
  JejuDorang/src/apis/diary.ts
  JejuDorang/src/apis/postLogin.ts
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/KakaoCallback/page.tsx
  JejuDorang/src/app/Main/page.tsx
  JejuDorang/src/components/Community/CommunityList/index.tsx
  JejuDorang/src/components/Community/index.tsx
  JejuDorang/src/components/DayRecord/CustomCalendar/index.tsx
  JejuDorang/src/components/DayRecord/index.tsx
  JejuDorang/src/components/LoginButton/index.tsx
  JejuDorang/src/types/Post.ts
Labels: ✨feat

#50 Dev feat/#47
  JejuDorang/src/app/App.css
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/index.css
Labels: 💄design

#51 Dev feat/#45
  JejuDorang/package-lock.json
  JejuDorang/package.json
  JejuDorang/src/apis/community.ts
  JejuDorang/src/apis/diary.ts
  JejuDorang/src/apis/getDiary.ts
  JejuDorang/src/app/KakaoCallback/page.tsx
  JejuDorang/src/app/Record/page.tsx
  JejuDorang/src/app/index.tsx
  JejuDorang/src/components/Community/Comment/index.tsx
  JejuDorang/src/components/Community/CommunityList/index.tsx
  JejuDorang/src/components/Community/List/index.tsx
  JejuDorang/src/components/Community/ListViewer/index.tsx
  JejuDorang/src/components/Community/WriteList/index.tsx
  JejuDorang/src/components/Community/index.tsx
  JejuDorang/src/components/DayRecord/CustomCalendar/index.tsx
  JejuDorang/src/components/DayRecord/Story/index.tsx
  JejuDorang/src/components/DayRecord/StoryViewer/index.tsx
  JejuDorang/src/components/DayRecord/WriteDiary/index.tsx
  JejuDorang/src/components/DayRecord/index.tsx
  JejuDorang/src/types/diary.ts
  JejuDorang/src/types/question.ts
  JejuDorang/src/types/storyItem.ts
  JejuDorang/src/types/streak.ts
  JejuDorang/tailwind.config.js
Labels: ✨feat

#53 Dev feat/#42
  JejuDorang/assets/img/back.svg
  JejuDorang/assets/img/chat/send.webp
  JejuDorang/assets/img/diaryDefault.webp
  JejuDorang/assets/img/myPage/diary/allView.webp
  JejuDorang/assets/img/myPage/diary/like.webp
  JejuDorang/assets/img/myPage/edit.webp
  JejuDorang/assets/img/myPage/locationMark.webp
  JejuDorang/src/apis/auth.ts
  JejuDorang/src/apis/diary.ts
  JejuDorang/src/apis/getDiary.ts
  JejuDorang/src/apis/postLogin.ts
  JejuDorang/src/app/AllDiaries/page.tsx
  JejuDorang/src/app/App.css
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/Dorang/page.tsx
  JejuDorang/src/app/EditMyPage/page.tsx
  JejuDorang/src/app/KakaoCallback/page.tsx
  JejuDorang/src/app/Main/page.tsx
  JejuDorang/src/app/MyPage/page.tsx
  JejuDorang/src/app/index.css
  JejuDorang/src/components/AchievementBox/index.tsx
  JejuDorang/src/components/AchievementList/Header/index.tsx
  JejuDorang/src/components/AchievementList/index.tsx
  JejuDorang/src/components/ChatDetail/Chat/DorangMessage/index.tsx
  JejuDorang/src/components/ChatDetail/Chat/Header/index.tsx
  JejuDorang/src/components/ChatDetail/Chat/InputMessage/index.tsx
  JejuDorang/src/components/ChatDetail/Chat/UserMessage/index.tsx
  JejuDorang/src/components/ChatDetail/Chat/index.tsx
  JejuDorang/src/components/ChatDetail/Onboarding/InterestBox/index.tsx
  JejuDorang/src/components/ChatDetail/Onboarding/index.tsx
  JejuDorang/src/components/ChatDetail/index.tsx
  JejuDorang/src/components/ChatMainHeader/index.tsx
  JejuDorang/src/components/Community/CommunityList/index.tsx
  JejuDorang/src/components/Community/index.tsx
  JejuDorang/src/components/DayRecord/CustomCalendar/index.css
  JejuDorang/src/components/DayRecord/CustomCalendar/index.tsx
  JejuDorang/src/components/DayRecord/Story/index.tsx
  JejuDorang/src/components/DayRecord/WriteDiary/index.tsx
  JejuDorang/src/components/DayRecord/index.tsx
  JejuDorang/src/components/DiaryPreviewBox/index.tsx
  JejuDorang/src/components/EditProfile/Header/index.tsx
  JejuDorang/src/components/EditProfile/Message/index.tsx
  JejuDorang/src/components/EditProfile/Place/index.tsx
  JejuDorang/src/components/EditProfile/Profile/index.tsx
  JejuDorang/src/components/EditProfile/Withdraw/index.tsx
  JejuDorang/src/components/EditProfile/index.tsx
  JejuDorang/src/components/LoginButton/index.tsx
  JejuDorang/src/components/MyPageAchievement/index.tsx
  JejuDorang/src/components/MyPageDiary/DiaryButton/index.tsx
  JejuDorang/src/components/MyPageDiary/index.tsx
  JejuDorang/src/components/MyPageProfile/index.tsx
  JejuDorang/src/components/Profile/index.tsx
  JejuDorang/src/constants/category.ts
  JejuDorang/src/constants/maxProfileDetailLength.ts
  JejuDorang/src/constants/maxTextLength.ts
  JejuDorang/src/constants/url.ts
  JejuDorang/src/types/Post.ts
  JejuDorang/src/types/chat.d.ts
  JejuDorang/src/types/diary.d.ts
Labels: ✨feat

#56 Dev feat/#42
  JejuDorang/assets/img/myPage/diary/allView.webp
  JejuDorang/assets/img/myPage/diary/like.webp
  JejuDorang/assets/img/myPage/edit.webp
  JejuDorang/assets/img/myPage/locationMark.webp
  JejuDorang/src/app/AllDiaries/page.tsx
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/EditMyPage/page.tsx
  JejuDorang/src/app/Main/page.tsx
  JejuDorang/src/app/MyPage/page.tsx
  JejuDorang/src/components/AchievementBox/index.tsx
  JejuDorang/src/components/AchievementList/Header/index.tsx
  JejuDorang/src/components/AchievementList/index.tsx
  JejuDorang/src/components/DiaryPreviewBox/index.tsx
  JejuDorang/src/components/EditProfile/Header/index.tsx
  JejuDorang/src/components/EditProfile/Message/index.tsx
  JejuDorang/src/components/EditProfile/Place/index.tsx
  JejuDorang/src/components/EditProfile/Profile/index.tsx
  JejuDorang/src/components/EditProfile/Withdraw/index.tsx
  JejuDorang/src/components/EditProfile/index.tsx
  JejuDorang/src/components/MyPageAchievement/index.tsx
  JejuDorang/src/components/MyPageDiary/DiaryButton/index.tsx
  JejuDorang/src/components/MyPageDiary/index.tsx
  JejuDorang/src/components/MyPageProfile/index.tsx
  JejuDorang/src/components/Profile/index.tsx
  JejuDorang/src/constants/category.ts
  JejuDorang/src/constants/maxProfileDetailLength.ts
  JejuDorang/src/types/diary.d.ts
Labels: ✨feat

#58 Dev refactor/#57
  JejuDorang/assets/img/errorPage.webp
  JejuDorang/netlify.toml
  JejuDorang/src/apis/community.ts
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/KakaoCallback/page.tsx
  JejuDorang/src/app/NotFound/page.tsx
  JejuDorang/src/app/Record/page.tsx
  JejuDorang/src/components/Community/Comment/index.tsx
  JejuDorang/src/components/Community/ListViewer/index.tsx
  JejuDorang/src/components/Community/WriteList/index.tsx
  JejuDorang/src/components/Community/index.tsx
  JejuDorang/src/components/DayRecord/CustomCalendar/index.tsx
  JejuDorang/src/components/DayRecord/WriteDiary/index.tsx
  JejuDorang/src/components/DayRecord/index.tsx
  JejuDorang/src/components/Spinner/index.css
  JejuDorang/src/components/Spinner/index.tsx
  JejuDorang/src/constants/maxTextLength.ts
  JejuDorang/tailwind.config.js
Labels: 🐞fix, ✨feat

#62 Dev feat/#61
  JejuDorang/assets/img/sorryEmoji.webp
  JejuDorang/src/apis/auth.ts
  JejuDorang/src/apis/index.ts
  JejuDorang/src/apis/main.ts
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/KakaoCallback/page.tsx
  JejuDorang/src/app/Main/page.tsx
  JejuDorang/src/app/NotFound/page.tsx
  JejuDorang/src/app/SettingDorang/page.tsx
  JejuDorang/src/components/ArroundKakaoMap/PlaceMarkers/index.tsx
  JejuDorang/src/components/ArroundKakaoMap/index.tsx
  JejuDorang/src/components/InvalidLocation/index.tsx
  JejuDorang/src/components/ItemBox/index.tsx
  JejuDorang/src/components/KakaoMap/index.tsx
  JejuDorang/src/components/MainDorang/Achievement/index.tsx
  JejuDorang/src/components/MainDorang/Character/index.tsx
  JejuDorang/src/components/MainDorang/LinkToDorang/index.tsx
  JejuDorang/src/components/MainDorang/Setting/index.tsx
  JejuDorang/src/components/MainDorang/index.tsx
  JejuDorang/src/components/MainModal/index.tsx
  JejuDorang/src/components/Profile/index.tsx
  JejuDorang/src/constants/url.ts
  JejuDorang/src/states/useAuthStore.ts
  JejuDorang/src/types/authStore.ts
  JejuDorang/src/types/information.ts
Labels: 💄design, ♻️refactor, ✨feat

#66 Dev feat/#61
  JejuDorang/assets/img/star.svg
  JejuDorang/index.html
  JejuDorang/public/favicon.webp
  JejuDorang/src/apis/stay.ts
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/RecommendStay/page.tsx
  JejuDorang/src/app/Stay/page.tsx
  JejuDorang/src/components/DayRecord/WriteDiary/index.tsx
  JejuDorang/src/components/Location/index.tsx
  JejuDorang/src/components/RecommendStay/index.tsx
  JejuDorang/src/components/StayCard/index.tsx
  JejuDorang/src/components/StayCategory/index.tsx
  JejuDorang/src/constants/maxTextLength.ts
  JejuDorang/src/types/Stays.ts
Labels: ✨feat

#69 Dev feat/#68
  JejuDorang/src/apis/auth.ts
  JejuDorang/src/apis/diary.ts
  JejuDorang/src/apis/index.ts
  JejuDorang/src/apis/main.ts
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/Main/page.tsx
  JejuDorang/src/app/SettingDorang/page.tsx
  JejuDorang/src/app/Stay/page.tsx
  JejuDorang/src/components/DayRecord/WriteDiary/index.tsx
  JejuDorang/src/components/Footer/index.tsx
  JejuDorang/src/components/ItemBox/index.tsx
  JejuDorang/src/components/MainDorang/Achievement/index.tsx
  JejuDorang/src/components/MainDorang/Character/index.tsx
  JejuDorang/src/components/MainDorang/index.tsx
  JejuDorang/src/components/MainModal/index.tsx
  JejuDorang/src/constants/itemList.ts
  JejuDorang/src/states/useAuthStore.ts
  JejuDorang/src/types/authStore.ts
  JejuDorang/src/types/diary.ts
  JejuDorang/src/types/dorangItem.ts
  JejuDorang/src/types/information.ts
  JejuDorang/src/utils/index.ts
Labels: 🐞fix, ✨feat

#71 merge: 주간머지
  JejuDorang/src/apis/auth.ts
  JejuDorang/src/apis/diary.ts
  JejuDorang/src/apis/index.ts
  JejuDorang/src/apis/main.ts
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/Main/page.tsx
  JejuDorang/src/app/SettingDorang/page.tsx
  JejuDorang/src/app/Stay/page.tsx
  JejuDorang/src/components/DayRecord/WriteDiary/index.tsx
  JejuDorang/src/components/Footer/index.tsx
  JejuDorang/src/components/ItemBox/index.tsx
  JejuDorang/src/components/MainDorang/Achievement/index.tsx
  JejuDorang/src/components/MainDorang/Character/index.tsx
  JejuDorang/src/components/MainDorang/index.tsx
  JejuDorang/src/components/MainModal/index.tsx
  JejuDorang/src/constants/itemList.ts
  JejuDorang/src/states/useAuthStore.ts
  JejuDorang/src/types/authStore.ts
  JejuDorang/src/types/diary.ts
  JejuDorang/src/types/dorangItem.ts
  JejuDorang/src/types/information.ts
  JejuDorang/src/utils/index.ts
Labels: Merge

#77 Dev feat/#70
  JejuDorang/assets/img/bookMark.svg
  JejuDorang/assets/img/searchIcon.svg
  JejuDorang/src/apis/auth.ts
  JejuDorang/src/apis/index.ts
  JejuDorang/src/apis/stay.ts
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/RecommendStay/page.tsx
  JejuDorang/src/app/Stay/page.tsx
  JejuDorang/src/components/Community/ListViewer/index.tsx
  JejuDorang/src/components/Community/index.tsx
  JejuDorang/src/components/StayCard/index.tsx
  JejuDorang/src/components/StayCategory/index.tsx
  JejuDorang/src/components/StayModal/index.tsx
  JejuDorang/src/types/Stays.ts
  JejuDorang/src/utils/render.tsx
  JejuDorang/tailwind.config.js
Labels: ✨feat

#80 Dev design/#76
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/DorangChatPage/page.tsx
  JejuDorang/src/components/AchievementBox/index.tsx
  JejuDorang/src/components/AchievementList/index.tsx
  JejuDorang/src/components/AcitivityDetail/DorangActivity/index.tsx
  JejuDorang/src/components/Chat/ChatHeader/index.tsx
  JejuDorang/src/components/Chat/InputMessage/index.tsx
  JejuDorang/src/components/Chat/index.tsx
  JejuDorang/src/components/EditProfile/Place/index.tsx
  JejuDorang/src/components/Footer/index.tsx
  JejuDorang/src/components/MyPageAchievement/index.tsx
  JejuDorang/src/components/MyPageDiary/DiaryButton/index.tsx
  JejuDorang/src/constants/category.ts
Labels: 💄design
