Repository Jeju-Dorang/Frontend, pull requests merged in 2024-08, with the labels that each got.

#7 ✨ feat: 라우팅기능
  JejuDorang/index.html
  JejuDorang/package-lock.json
  JejuDorang/package.json
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/Main/page.tsx
  JejuDorang/src/app/index.tsx
  JejuDorang/src/app/main.tsx
  JejuDorang/tsconfig.json
Labels: ✨feat

#10 merge: dev to main
  JejuDorang/.gitignore
  JejuDorang/README.md
  JejuDorang/index.html
  JejuDorang/package-lock.json
  JejuDorang/package.json
  JejuDorang/postcss.config.js
  JejuDorang/src/App.tsx
  JejuDorang/src/app/App.css
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/Main/page.tsx
  JejuDorang/src/app/README.md
  JejuDorang/src/app/index.css
  JejuDorang/src/app/index.tsx
  JejuDorang/src/components/README.md
  JejuDorang/src/constants/README.md
  JejuDorang/src/hooks/README.md
  JejuDorang/src/index.css
  JejuDorang/src/main.tsx
  JejuDorang/src/states/README.md
  JejuDorang/src/styles/README.md
  JejuDorang/src/types/README.md
  JejuDorang/src/utils/README.md
  JejuDorang/src/vite-env.d.ts
  JejuDorang/tailwind.config.js
  JejuDorang/tsconfig.json
  JejuDorang/vite.config.ts
  README.md
Labels: Merge

#15 feat: 경로 설정추가
  JejuDorang/assets/img/profile.webp
  JejuDorang/package-lock.json
  JejuDorang/package.json
  JejuDorang/src/app/Main/page.tsx
  JejuDorang/src/components/Profile/index.tsx
  JejuDorang/tsconfig.json
  JejuDorang/vite.config.ts
Labels: ✨feat

#16 feat: 프로필 컴포넌트 구현
  JejuDorang/src/app/Main/page.tsx
  JejuDorang/src/components/Profile/index.tsx
  JejuDorang/src/types/image.d.ts
Labels: ✨feat

#18 Dev feat/#8
  JejuDorang/.gitignore
  JejuDorang/assets/img/dorangProfile.webp
  JejuDorang/package-lock.json
  JejuDorang/package.json
  JejuDorang/src/app/Main/page.tsx
  JejuDorang/src/components/AchievementBox/index.tsx
  JejuDorang/src/components/StayBox/index.tsx
  JejuDorang/yarn.lock
Labels: ✨feat

#20 Dev feat/#13
  JejuDorang/index.html
  JejuDorang/package-lock.json
  JejuDorang/package.json
  JejuDorang/src/app/Main/page.tsx
  JejuDorang/src/components/ArroundKakaoMap/PlaceMarkers.tsx
  JejuDorang/src/components/ArroundKakaoMap/index.tsx
  JejuDorang/src/components/KakaoMap/index.tsx
  JejuDorang/src/components/MainModal/index.tsx
  JejuDorang/src/components/Profile/index.tsx
  JejuDorang/src/constants/category.ts
  JejuDorang/src/types/categorycode.d.ts
  JejuDorang/src/types/place.d.ts
  JejuDorang/tsconfig.json
  JejuDorang/vite.config.ts
Labels: ✨feat

#24 Dev feat/#11
  JejuDorang/.gitignore
  JejuDorang/assets/img/info.svg
  JejuDorang/assets/img/refresh.webp
  JejuDorang/package-lock.json
  JejuDorang/src/app/Activity/page.tsx
  JejuDorang/src/app/App.tsx
  JejuDorang/src/components/AchievementBox/index.tsx
  JejuDorang/src/components/AcitivityDetail/DorangActivity/index.tsx
  JejuDorang/src/components/AcitivityDetail/LocationActivity/ActivityKakaoMap/PlaceActivity.tsx
  JejuDorang/src/components/AcitivityDetail/LocationActivity/ActivityKakaoMap/index.tsx
  JejuDorang/src/components/AcitivityDetail/LocationActivity/index.tsx
  JejuDorang/src/components/AcitivityDetail/index.tsx
  JejuDorang/src/components/StayBox/index.tsx
  JejuDorang/src/types/achievement.d.ts
  JejuDorang/src/types/categorycode.d.ts
  JejuDorang/src/types/image.d.ts
  JejuDorang/src/types/stay.d.ts
  JejuDorang/yarn.lock
Labels: ✨feat

#21 Dev feat/#13
  JejuDorang/assets/img/dorang/background/forest.webp
  JejuDorang/assets/img/dorang/background/market.webp
  JejuDorang/assets/img/dorang/background/museum.webp
  JejuDorang/assets/img/dorang/defaultDorang.webp
  JejuDorang/assets/img/dorang/item/boat.webp
  JejuDorang/assets/img/dorang/item/camera.webp
  JejuDorang/assets/img/dorang/item/orange.webp
  JejuDorang/assets/img/dorang/item/peanut.webp
  JejuDorang/assets/img/dorang/item/pencil.webp
  JejuDorang/assets/img/dorang/item/shrimp.webp
  JejuDorang/assets/img/dorang/item/teddyBear.webp
  JejuDorang/assets/img/dorang/pet/alpaca.webp
  JejuDorang/assets/img/dorang/pet/blackPig.webp
  JejuDorang/assets/img/dorangChat.webp
  JejuDorang/assets/img/setting.webp
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/Main/page.tsx
  JejuDorang/src/app/SettingDorang/page.tsx
  JejuDorang/src/components/ArroundKakaoMap/index.tsx
  JejuDorang/src/components/ItemBox/index.tsx
  JejuDorang/src/components/MainDorang/Achievement.tsx
  JejuDorang/src/components/MainDorang/Character.tsx
  JejuDorang/src/components/MainDorang/DorangChat.tsx
  JejuDorang/src/components/MainDorang/LinkToDorang.tsx
  JejuDorang/src/components/MainDorang/Setting.tsx
  JejuDorang/src/components/MainDorang/index.tsx
  JejuDorang/src/components/MainModal/index.tsx
  JejuDorang/src/constants/category.ts
  JejuDorang/src/constants/itemList.ts
  JejuDorang/tailwind.config.js
Labels: ✨feat

#26 Dev feat/#22
  JejuDorang/src/app/SettingDorang/page.tsx
  JejuDorang/src/components/ArroundKakaoMap/PlaceMarkers/PlaceMarkers.tsx
  JejuDorang/src/components/ArroundKakaoMap/PlaceMarkers/index.tsx
  JejuDorang/src/components/ArroundKakaoMap/index.tsx
  JejuDorang/src/components/MainDorang/Achievement/index.tsx
  JejuDorang/src/components/MainDorang/Character/index.tsx
  JejuDorang/src/components/MainDorang/DorangChat/index.tsx
  JejuDorang/src/components/MainDorang/LinkToDorang/index.tsx
  JejuDorang/src/components/MainDorang/Setting/index.tsx
  JejuDorang/src/components/MainDorang/index.tsx
  JejuDorang/src/constants/itemList.ts
  JejuDorang/yarn.lock
Labels: 🐞fix

#27 Dev feat/#22
  JejuDorang/src/apis/README.md
  JejuDorang/src/apis/index.tsx
  JejuDorang/src/components/ArroundKakaoMap/PlaceMarkers/PlaceMarkers.tsx
  JejuDorang/src/components/ArroundKakaoMap/PlaceMarkers/index.tsx
  JejuDorang/src/components/ArroundKakaoMap/index.tsx
  JejuDorang/src/states/useAuthStore.ts
  JejuDorang/src/styles/README.md
  JejuDorang/src/types/achievement.d.ts
  JejuDorang/src/types/authStore.ts
Labels: ✨feat

#28 Dev feat/#23
  JejuDorang/assets/img/maps/mapEast.webp
  JejuDorang/assets/img/maps/mapNorth.webp
  JejuDorang/assets/img/maps/mapSouth.webp
  JejuDorang/assets/img/maps/mapWest.webp
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/Stay/index.css
  JejuDorang/src/app/Stay/page.tsx
  JejuDorang/src/components/ArroundKakaoMap/index.tsx
  JejuDorang/src/components/EstimatePrice/index.css
  JejuDorang/src/components/EstimatePrice/index.tsx
  JejuDorang/src/components/ItemBox/index.tsx
  JejuDorang/src/components/Location/index.tsx
  JejuDorang/src/components/StayCategory/index.tsx
  JejuDorang/src/constants/category.ts
  JejuDorang/src/constants/itemList.ts
  JejuDorang/src/constants/maps.ts
Labels: ✨feat

#29 Dev feat/#19
  JejuDorang/assets/img/footer/Clicked/activity.webp
  JejuDorang/assets/img/footer/Clicked/chat.webp
  JejuDorang/assets/img/footer/Clicked/home.webp
  JejuDorang/assets/img/footer/Clicked/record.webp
  JejuDorang/assets/img/footer/Clicked/user.webp
  JejuDorang/assets/img/footer/notClicked/activity.webp
  JejuDorang/assets/img/footer/notClicked/chat.webp
  JejuDorang/assets/img/footer/notClicked/home.webp
  JejuDorang/assets/img/footer/notClicked/record.webp
  JejuDorang/assets/img/footer/notClicked/user.webp
  JejuDorang/src/app/Activity/page.tsx
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/Dorang/page.tsx
  JejuDorang/src/components/AcitivityDetail/index.tsx
  JejuDorang/src/components/ChatDetail/Chat/DorangMessage/index.tsx
  JejuDorang/src/components/ChatDetail/Chat/InputMessage/index.tsx
  JejuDorang/src/components/ChatDetail/Chat/UserMessage/index.tsx
  JejuDorang/src/components/ChatDetail/Chat/index.tsx
  JejuDorang/src/components/ChatDetail/Onboarding/InterestBox/index.tsx
  JejuDorang/src/components/ChatDetail/Onboarding/index.tsx
  JejuDorang/src/components/ChatDetail/index.tsx
  JejuDorang/src/components/ChatHeader/index.tsx
  JejuDorang/src/components/Footer/index.tsx
  JejuDorang/src/constants/interests.ts
  JejuDorang/src/types/footerTarget.ts
Labels: ✨feat

#34 Dev feat/#25
  JejuDorang/assets/img/login/jejuDorang.webp
  JejuDorang/assets/img/login/kakaoLogin.webp
  JejuDorang/src/apis/index.tsx
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/Login/page.tsx
  JejuDorang/src/app/Main/page.tsx
  JejuDorang/src/components/LoginButton/index.tsx
  JejuDorang/tsconfig.json
Labels: ✨feat

#36 Dev feat/#35
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/Record/page.tsx
  JejuDorang/src/components/Community/index.tsx
  JejuDorang/src/components/Diary/index.tsx
  JejuDorang/src/components/LoginButton/index.tsx
  JejuDorang/src/components/Story/index.tsx
  JejuDorang/src/types/storyItem.ts
Labels: ✨feat
