Repository Jeju-Dorang/Frontend, pull requests merged in 2024-10, with the labels that each got.

#82 Dev design/#76
  JejuDorang/src/app/AllDiaries/page.tsx
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/DorangChatPage/page.tsx
  JejuDorang/src/components/AchievementBox/index.tsx
  JejuDorang/src/components/AchievementList/index.tsx
  JejuDorang/src/components/AcitivityDetail/DorangActivity/index.tsx
  JejuDorang/src/components/Chat/ChatHeader/index.tsx
  JejuDorang/src/components/Chat/InputMessage/index.tsx
  JejuDorang/src/components/Chat/index.tsx
  JejuDorang/src/components/EditProfile/Place/SelectModal/index.tsx
  JejuDorang/src/components/EditProfile/Place/index.tsx
  JejuDorang/src/components/EditProfile/Withdraw/index.tsx
  JejuDorang/src/components/Footer/index.tsx
  JejuDorang/src/components/MyPageAchievement/index.tsx
  JejuDorang/src/components/MyPageDiary/DiaryButton/index.tsx
  JejuDorang/src/components/MyPageProfile/index.tsx
  JejuDorang/src/components/StayBox/index.tsx
  JejuDorang/src/components/ViewDiary/index.tsx
  JejuDorang/src/constants/category.ts
  JejuDorang/src/types/diary.ts
Labels: 💄design

#84 Dev design/#76
  JejuDorang/src/app/AllDiaries/page.tsx
  JejuDorang/src/components/AchievementBox/index.tsx
  JejuDorang/src/components/AchievementList/index.tsx
  JejuDorang/src/components/AcitivityDetail/DorangActivity/index.tsx
  JejuDorang/src/components/Chat/index.tsx
  JejuDorang/src/components/EditProfile/Place/SelectModal/index.tsx
  JejuDorang/src/components/EditProfile/Place/index.tsx
  JejuDorang/src/components/EditProfile/Withdraw/index.tsx
  JejuDorang/src/components/MyPageAchievement/index.tsx
  JejuDorang/src/components/MyPageDiary/DiaryButton/index.tsx
  JejuDorang/src/components/MyPageProfile/index.tsx
  JejuDorang/src/components/StayBox/index.tsx
  JejuDorang/src/components/ViewDiary/index.tsx
  JejuDorang/src/types/diary.ts
Labels: 💄design

#85 merge: 최종기능머지
  JejuDorang/package-lock.json
  JejuDorang/package.json
  JejuDorang/src/app/Main/page.tsx
  JejuDorang/src/app/RecommendStay/page.tsx
  JejuDorang/src/app/Record/page.tsx
  JejuDorang/src/components/AchievementBox/index.tsx
  JejuDorang/src/components/AchievementList/index.tsx
  JejuDorang/src/components/AcitivityDetail/DorangActivity/index.tsx
  JejuDorang/src/components/Community/List/index.tsx
  JejuDorang/src/components/Community/ListViewer/index.tsx
  JejuDorang/src/components/Community/index.tsx
  JejuDorang/src/components/DayRecord/Story/index.tsx
  JejuDorang/src/components/DayRecord/StoryViewer/index.tsx
  JejuDorang/src/components/DayRecord/WriteDiary/index.tsx
  JejuDorang/src/components/DayRecord/index.tsx
  JejuDorang/src/components/InvalidLocation/index.tsx
  JejuDorang/src/components/MainDorang/Achievement/index.tsx
  JejuDorang/src/components/MainDorang/index.tsx
  JejuDorang/src/components/MainModal/index.tsx
  JejuDorang/src/components/MyPageAchievement/index.tsx
  JejuDorang/src/components/StayCategory/index.tsx
  JejuDorang/src/states/useAuthStore.ts
  JejuDorang/src/types/authStore.ts
  JejuDorang/src/types/information.ts
Labels: Merge

#87 merge: 빌드 버그 수정
  JejuDorang/src/app/DorangChatPage/page.tsx
  JejuDorang/src/components/EditProfile/Place/index.tsx
Labels: 🐞fix

#91 Dev2
  JejuDorang/src/app/AllDiaries/page.tsx
  JejuDorang/src/components/AchievementBox/index.tsx
  JejuDorang/src/components/AchievementList/index.tsx
  JejuDorang/src/components/AcitivityDetail/DorangActivity/index.tsx
  JejuDorang/src/components/Chat/index.tsx
  JejuDorang/src/components/EditProfile/Place/SelectModal/index.tsx
  JejuDorang/src/components/EditProfile/Place/index.tsx
  JejuDorang/src/components/EditProfile/Withdraw/index.tsx
  JejuDorang/src/components/MyPageAchievement/index.tsx
  JejuDorang/src/components/MyPageDiary/DiaryButton/index.tsx
  JejuDorang/src/components/MyPageProfile/index.tsx
  JejuDorang/src/components/StayBox/index.tsx
  JejuDorang/src/components/ViewDiary/index.tsx
  JejuDorang/src/types/diary.ts
Labels: Merge

#93 Dev fix/#92
  JejuDorang/src/app/DorangChatPage/page.tsx
  JejuDorang/src/components/AchievementBox/index.tsx
  JejuDorang/src/components/AchievementList/index.tsx
  JejuDorang/src/components/AcitivityDetail/DorangActivity/index.tsx
  JejuDorang/src/components/Chat/ChatHeader/index.tsx
  JejuDorang/src/components/Chat/InputMessage/index.tsx
  JejuDorang/src/components/Chat/index.tsx
  JejuDorang/src/components/Footer/index.tsx
  JejuDorang/src/components/MyPageAchievement/index.tsx
  JejuDorang/src/components/MyPageDiary/DiaryButton/index.tsx
  JejuDorang/src/components/ViewDiary/index.tsx
  JejuDorang/src/constants/category.ts
Labels: 🐞fix

#94 Dev feat/#88
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/DorangChatPage/page.tsx
  JejuDorang/src/app/RecommendStay/page.tsx
  JejuDorang/src/app/SettingDorang/page.tsx
  JejuDorang/src/components/AchievementBox/index.tsx
  JejuDorang/src/components/AchievementList/index.tsx
  JejuDorang/src/components/AcitivityDetail/DorangActivity/index.tsx
  JejuDorang/src/components/Chat/ChatHeader/index.tsx
  JejuDorang/src/components/Chat/InputMessage/index.tsx
  JejuDorang/src/components/Chat/index.tsx
  JejuDorang/src/components/Community/index.tsx
  JejuDorang/src/components/DayRecord/StoryViewer/index.tsx
  JejuDorang/src/components/DayRecord/WriteDiary/index.tsx
  JejuDorang/src/components/DayRecord/index.tsx
  JejuDorang/src/components/Footer/index.tsx
  JejuDorang/src/components/MyPageAchievement/index.tsx
  JejuDorang/src/components/MyPageDiary/DiaryButton/index.tsx
  JejuDorang/src/components/StayCard/index.tsx
  JejuDorang/src/components/StayModal/index.tsx
  JejuDorang/src/components/ViewDiary/index.tsx
  JejuDorang/src/constants/category.ts
Labels: 🐞fix, 💄design, ✨feat

#95 Merge: 버그수정 병합
  JejuDorang/src/app/App.tsx
  JejuDorang/src/app/DorangChatPage/page.tsx
  JejuDorang/src/app/RecommendStay/page.tsx
  JejuDorang/src/app/SettingDorang/page.tsx
  JejuDorang/src/components/AchievementBox/index.tsx
  JejuDorang/src/components/AchievementList/index.tsx
  JejuDorang/src/components/AcitivityDetail/DorangActivity/index.tsx
  JejuDorang/src/components/Chat/ChatHeader/index.tsx
  JejuDorang/src/components/Chat/InputMessage/index.tsx
  JejuDorang/src/components/Chat/index.tsx
  JejuDorang/src/components/Community/index.tsx
  JejuDorang/src/components/DayRecord/StoryViewer/index.tsx
  JejuDorang/src/components/DayRecord/WriteDiary/index.tsx
  JejuDorang/src/components/DayRecord/index.tsx
  JejuDorang/src/components/Footer/index.tsx
  JejuDorang/src/components/MyPageAchievement/index.tsx
  JejuDorang/src/components/MyPageDiary/DiaryButton/index.tsx
  JejuDorang/src/components/StayCard/index.tsx
  JejuDorang/src/components/StayModal/index.tsx
  JejuDorang/src/components/ViewDiary/index.tsx
  JejuDorang/src/constants/category.ts
Labels: Merge

#98 Dev feat/#96
  JejuDorang/src/components/Chat/index.tsx
  JejuDorang/src/components/Community/index.tsx
  JejuDorang/src/components/DayRecord/index.tsx
  JejuDorang/src/components/MainDorang/DorangChat/index.tsx
  JejuDorang/src/utils/render.tsx
Labels: 🐞fix

#97 ⬆️ Chore : useEffect 수정
  JejuDorang/src/app/MyPage/page.tsx
  JejuDorang/src/components/AchievementBox/index.tsx
  JejuDorang/src/components/AchievementList/index.tsx
  JejuDorang/src/components/AcitivityDetail/DorangActivity/index.tsx
  JejuDorang/src/components/EditProfile/Place/index.tsx
  JejuDorang/src/components/MyPageAchievement/index.tsx
Labels: 🔧chore

#99 Merge: 찐찐최종 merge
  JejuDorang/src/app/MyPage/page.tsx
  JejuDorang/src/components/AchievementBox/index.tsx
  JejuDorang/src/components/AchievementList/index.tsx
  JejuDorang/src/components/AcitivityDetail/DorangActivity/index.tsx
  JejuDorang/src/components/Community/index.tsx
  JejuDorang/src/components/DayRecord/index.tsx
  JejuDorang/src/components/EditProfile/Place/index.tsx
  JejuDorang/src/components/MainDorang/DorangChat/index.tsx
  JejuDorang/src/components/MyPageAchievement/index.tsx
  JejuDorang/src/utils/render.tsx
Labels: 🐞fix
